# Generated by Django 3.1.4 on 2020-12-06 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency_name', models.CharField(choices=[('PLN_PLN', 'PLN'), ('EUR_PLN', 'EUR'), ('USD_PLN', 'USD'), ('JPY_PLN', 'JPY'), ('GBP_PLN', 'GBP'), ('SupEuro', 'SupremeEuro')], max_length=10, primary_key=True, serialize=False, unique=True)),
                ('exchange_rate_to_pln', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Unrecognised Item', max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('url', models.CharField(max_length=300)),
                ('site_name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('37', '37'), ('37.5', '37.5'), ('38', '38'), ('38.5', '38.5'), ('39', '39'), ('39.5', '39.5'), ('40', '40'), ('40.5', '40.5'), ('41', '41'), ('41.5', '41.5'), ('42', '42'), ('42.5', '42.5'), ('43', '43'), ('44', '44'), ('44.5', '44.5'), ('45', '45'), ('45.5', '45.5')], max_length=4)),
                ('image', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(default='PLN', on_delete=models.SET('PLN'), to='itemsBrowser.currencies')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
